sudo: false
language: python
dist:
  - xenial
  # - bionic
services:
  - mongodb
  - memcached
addons:
  apt:
    packages:
    - rabbitmq-server
before_install:
  # If the last tag is more than 50 commits away, we need to fetch more for
  # the scm_version module to determine the version.
  - git fetch --depth=1000
matrix:
  include:
  - os: linux
    python: "2.7"
  - os: linux
    python: "3.5"
  - os: linux
    python: "3.6"
  - os: linux
    python: "3.7"
  - os: osx
    language: sh
    addons:
      homebrew:
        update: true
        packages:
        - python3
        - memcached
        - libmemcached
        - rabbitmq
        - node
        - libtiff
        - openslide
        - gdal
        - mapnik
        - vips
        - proj
        # needed for python-mapnik
        # - boost-python3
    before_install:
      - git fetch --depth=1000
      # Don't install or test mapnik source until we figure out how to install
      # python-mapnik in travis.
      - sed -i '' 's/-e sources\/mapnik/# -e sources\/mapnik/g' requirements-dev.txt
      - echo 'git+https://github.com/manthey/pylibtiff@wheel-support#egg=libtiff' >> requirements-dev.txt
      - rm test/test_source_mapnik.py
      # - export BOOST_PYTHON_LIB=boost_python37
      # - pip install git+https://github.com/mapnik/python-mapnik
      - pip3 install virtualenv
      - virtualenv -p python3 ~/venv
      - source ~/venv/bin/activate
      - curl https://fastdl.mongodb.org/osx/mongodb-macos-x86_64-4.2.0.tgz -o mongodb.tgz
      - mkdir mongodb
      - tar -zxvf mongodb.tgz -C mongodb --strip-components 1
      - mkdir -p `pwd`/data/db
      - mongodb/bin/mongod --dbpath `pwd`/data/db --logpath `pwd`/mongodb.log --fork
      - rabbitmq-server
      - brew services start memcached
      - npm install -g npm
    env:
      - TRAVIS_PYTHON_VERSION=3.7
install:
  - pip install --upgrade pip
  - pip install --upgrade virtualenv
  - pip install tox-travis
script:
  # Piping through cat does less buffering of the output but can consume the
  # exit code
  #   Deselect the test_conversion tests, as the virtualenv travis uses fails
  # to import pyvips with an error
  # "OSError: dlopen: cannot load any more object with static TLS"
  - tox -- -k 'not test_conversion' | cat; test ${PIPESTATUS[0]} -eq 0
after_success:
  - pip install codecov
  - codecov --disable search pycov gcov --file build/test/coverage/py_coverage.xml build/test/coverage/cobertura-coverage.xml
