version: "3"
services:
  mongodb:
    image: "mongo:3.6"
    ports:
      - "27017"
  large_image:
    volumes:
      - ../../:/large_image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - mongodb
    container_name: large-image-mapnik-python36
